### ISSUE TITLE
[BUG] Trigger Happy integration broken

### ISSUE THREAD

**Issue by Zamrod** [CDeenen/SharedVision#12] opened 2021-12-20 18:09 UTC
**Setup**
 - OS: Window 10
 - Browser: Firefox
 - Module version: 1.0.7
 - Foundry version: V9 Testing 3 (Build 236)
 - Gaming system & version: dnd5e 1.5.6
 - Any other modules enabled: yes (just libwrapper)

**Describe the bug**
Errors come up for players when loading into the game:

```
TypeError: Error thrown in hooked function '' for hook 'controlToken': game.triggers is undefined
[Detected 1 package: SharedVision]
    triggerHappy_ControlToken http://192.168.1.70:30001/modules/SharedVision/src/externalModules.js:95
    <anonymous> http://192.168.1.70:30001/modules/SharedVision/sharedvision.js:19
    _call http://192.168.1.70:30001/scripts/foundry.js:304
    callAll http://192.168.1.70:30001/scripts/foundry.js:263
    control http://192.168.1.70:30001/scripts/foundry.js:21401
    _initializeTokenControl http://192.168.1.70:30001/scripts/foundry.js:20052
    _initialize http://192.168.1.70:30001/scripts/foundry.js:19967
```

**Comment by CDeenen** [comment] 2021-12-22 10:57
Thanks for the bug report. 
I can reproduce this. It doesn't seem to cause any issues, as long as you're not trying to use the Trigger Happy integration. If it does cause issues for you (besides not being able to use TH), please let me know.
If TH is not enabled, it shouldn't even call this, so I'll try to get that fixed. TH integration is currently not going to work, due to a change in TH (see [here](https://github.com/League-of-Foundry-Developers/fvtt-module-trigger-happy/issues/76)), which will hopefully be fixed in the future.

**Closed** 2022-07-05 03:42 UTC
Labels: bug
